#!/usr/bin/env python3
"""LeetCode solved-problems syncer with auto-generated revision notes.

Produces ONE file: solved.md — all your accepted problems, grouped by topic,
each with the problem statement, your submitted code, and a 3-line revision
note (Pattern / Key idea / Complexity) generated by the `claude` CLI.

Usage:
    python3 sync.py                    # fetch only new problems + rebuild solved.md
    python3 sync.py --full             # re-fetch every problem (overwrites cache)
    python3 sync.py --regen-notes      # regenerate all intuition notes
    python3 sync.py --no-notes         # skip claude-generated notes (faster)
    python3 sync.py --problem two-sum  # sync just one problem by titleSlug

Session cookie:
    Read from $LEETCODE_SESSION env var, or ~/.leetcode/session file.
    Refresh from browser DevTools > Application > Cookies > leetcode.com > LEETCODE_SESSION.

Intuition notes:
    Uses `claude --print --model claude-haiku-4-5-20251001` (Claude Code CLI).
    Cached in state.json; only new problems trigger new calls.
"""

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import time
from collections import Counter, defaultdict
from html import unescape
from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUTPUT_MD = ROOT / "solved.md"
STATE_FILE = ROOT / "state.json"          # cache: problem data + code + intuition
LEGACY_STATE = ROOT / "solved.json"       # migrate away from this

THROTTLE_SEC = 0.6
CLAUDE_MODEL = "claude-haiku-4-5-20251001"

Q_LIST = """
query problemsetQuestionList($skip:Int!,$limit:Int!,$filters:QuestionListFilterInput) {
  problemsetQuestionList: questionList(categorySlug:"", limit:$limit, skip:$skip, filters:$filters) {
    total: totalNum
    questions: data {
      acRate difficulty
      frontendQuestionId: questionFrontendId
      title titleSlug
      topicTags { name slug }
    }
  }
}"""

Q_QUESTION = """
query questionData($titleSlug: String!) {
  question(titleSlug: $titleSlug) {
    content
    difficulty
    hints
  }
}"""

Q_SUBMISSIONS = """
query submissionList($slug: String!) {
  questionSubmissionList(offset: 0, limit: 20, questionSlug: $slug) {
    submissions {
      id statusDisplay lang timestamp runtime memory
    }
  }
}"""

Q_SUBDETAIL = """
query submissionDetails($id: Int!) {
  submissionDetails(submissionId: $id) {
    code
    runtime memory timestamp statusCode
    lang { name verboseName }
  }
}"""

LANG_MAP = {
    "python": "python", "python3": "python", "cpp": "cpp", "java": "java",
    "javascript": "javascript", "typescript": "typescript", "c": "c",
    "csharp": "csharp", "go": "go", "rust": "rust", "kotlin": "kotlin",
    "swift": "swift", "ruby": "ruby", "scala": "scala", "php": "php",
    "mysql": "sql", "mssql": "sql", "oraclesql": "sql", "postgresql": "sql",
    "pythonml": "python", "pythondata": "python", "bash": "bash",
    "racket": "racket", "elixir": "elixir", "erlang": "erlang", "dart": "dart",
}


def get_session():
    env = os.environ.get("LEETCODE_SESSION")
    if env and env.strip():
        return env.strip()
    p = Path.home() / ".leetcode" / "session"
    if p.exists():
        return p.read_text().strip()
    sys.exit(
        "No session cookie found. Either:\n"
        "  export LEETCODE_SESSION='<cookie value>'\n"
        "or put it in ~/.leetcode/session (chmod 600).\n"
        "Grab from browser DevTools > Application > Cookies > leetcode.com > LEETCODE_SESSION."
    )


def gql(session, query, variables, referer="https://leetcode.com/problemset/"):
    body = json.dumps({"query": query, "variables": variables})
    result = subprocess.run(
        [
            "curl", "-sS", "--max-time", "30",
            "-X", "POST", "https://leetcode.com/graphql",
            "-H", "Content-Type: application/json",
            "-H", "User-Agent: Mozilla/5.0",
            "-H", f"Referer: {referer}",
            "-H", f"Cookie: LEETCODE_SESSION={session}",
            "--data-binary", "@-",
            "-w", "\n__HTTP__%{http_code}",
        ],
        input=body, capture_output=True, text=True,
    )
    if result.returncode != 0:
        raise RuntimeError(f"curl failed (rc={result.returncode}): {result.stderr.strip() or result.stdout.strip()[:300]}")
    out = result.stdout
    m = re.search(r"__HTTP__(\d+)\s*$", out)
    http = int(m.group(1)) if m else 0
    payload = out[: m.start()] if m else out
    if http in (401, 403):
        sys.exit(
            f"Auth failed ({http}). Session cookie is expired or invalid.\n"
            "Refresh it: log in to leetcode.com, copy LEETCODE_SESSION from DevTools > Cookies,\n"
            "then update ~/.leetcode/session."
        )
    if http >= 400:
        raise RuntimeError(f"HTTP {http}: {payload[:300]}")
    data = json.loads(payload)
    if "errors" in data:
        raise RuntimeError(f"GraphQL error: {data['errors']}")
    return data["data"]


def fetch_ac_list(session):
    all_q, skip, limit = [], 0, 100
    while True:
        d = gql(session, Q_LIST, {"skip": skip, "limit": limit, "filters": {"status": "AC"}})
        block = d["problemsetQuestionList"]
        all_q.extend(block["questions"])
        if len(all_q) >= block["total"] or not block["questions"]:
            break
        skip += limit
        time.sleep(THROTTLE_SEC)
    return all_q


def fetch_question(session, slug):
    return gql(session, Q_QUESTION, {"titleSlug": slug},
               referer=f"https://leetcode.com/problems/{slug}/")["question"]


def fetch_latest_ac_submission(session, slug):
    d = gql(session, Q_SUBMISSIONS, {"slug": slug},
            referer=f"https://leetcode.com/problems/{slug}/submissions/")
    subs = d["questionSubmissionList"]["submissions"] or []
    for s in subs:
        if s["statusDisplay"] == "Accepted":
            return s
    return None


def fetch_submission_detail(session, sub_id):
    return gql(session, Q_SUBDETAIL, {"id": int(sub_id)},
               referer=f"https://leetcode.com/submissions/detail/{sub_id}/")["submissionDetails"]


def html_to_md(html):
    if not html:
        return "_(no problem statement returned)_"
    # LeetCode HTML often contains embedded \r\n / \r — normalize to \n so output is
    # deterministic across platforms (macOS vs Linux CI) and doesn't churn on every run.
    s = html.replace("\r\n", "\n").replace("\r", "\n")
    s = re.sub(r"<pre>(.*?)</pre>",
               lambda m: "\n```\n" + m.group(1).strip() + "\n```\n",
               s, flags=re.DOTALL)
    s = re.sub(r"<code>(.*?)</code>", r"`\1`", s, flags=re.DOTALL)
    s = re.sub(r"<strong>(.*?)</strong>", r"**\1**", s, flags=re.DOTALL)
    s = re.sub(r"<b>(.*?)</b>", r"**\1**", s, flags=re.DOTALL)
    s = re.sub(r"<em>(.*?)</em>", r"*\1*", s, flags=re.DOTALL)
    s = re.sub(r"<i>(.*?)</i>", r"*\1*", s, flags=re.DOTALL)
    s = re.sub(r"<sup>(.*?)</sup>", r"^\1", s, flags=re.DOTALL)
    s = re.sub(r"<sub>(.*?)</sub>", r"_\1", s, flags=re.DOTALL)
    s = re.sub(r"<li>(.*?)</li>", r"- \1", s, flags=re.DOTALL)
    s = re.sub(r"</?ul>", "\n", s)
    s = re.sub(r"</?ol>", "\n", s)
    s = re.sub(r"<br\s*/?>", "\n", s)
    s = re.sub(r"</p>", "\n\n", s)
    s = re.sub(r"<p[^>]*>", "", s)
    s = re.sub(r"<[^>]+>", "", s)
    s = unescape(s)
    s = re.sub(r"\n{3,}", "\n\n", s)
    return s.strip()


INTUITION_PROMPT = """You are helping a software engineer prepare for interviews by writing a compact revision note for a LeetCode problem they solved. Look at the problem and their submitted code, then output EXACTLY 3 lines in this format (no preamble, no follow-up, no markdown headers):

Pattern: <2-6 word name of the technique (e.g. "Two pointers", "Sliding window + hashmap", "Top-down DP with memo", "Monotonic stack")>
Key idea: <ONE sentence, max 25 words, explaining WHY this approach works — the insight, not the mechanics>
Complexity: <O(...) time / O(...) space>

Problem: {title}
Difficulty: {difficulty}

Statement:
{statement}

Their code ({lang}):
```
{code}
```
"""


def _intuition_via_api(prompt, api_key):
    """POST to Anthropic Messages API via curl. Returns text or None."""
    body = json.dumps({
        "model": CLAUDE_MODEL,
        "max_tokens": 200,
        "messages": [{"role": "user", "content": prompt}],
    })
    r = subprocess.run(
        [
            "curl", "-sS", "--max-time", "60",
            "-X", "POST", "https://api.anthropic.com/v1/messages",
            "-H", f"x-api-key: {api_key}",
            "-H", "anthropic-version: 2023-06-01",
            "-H", "content-type: application/json",
            "--data-binary", "@-",
            "-w", "\n__HTTP__%{http_code}",
        ],
        input=body, capture_output=True, text=True,
    )
    if r.returncode != 0:
        print(f"      (anthropic api curl failed: {r.stderr.strip()[:200]})")
        return None
    out = r.stdout
    m = re.search(r"__HTTP__(\d+)\s*$", out)
    http = int(m.group(1)) if m else 0
    payload = out[: m.start()] if m else out
    if http >= 400:
        print(f"      (anthropic api HTTP {http}: {payload[:200]})")
        return None
    try:
        data = json.loads(payload)
        blocks = data.get("content") or []
        text = "".join(b.get("text", "") for b in blocks if b.get("type") == "text")
        return text.strip() or None
    except Exception as e:
        print(f"      (anthropic api parse error: {e})")
        return None


def _intuition_via_cli(prompt):
    """Call local `claude --print`. Returns text or None."""
    try:
        r = subprocess.run(
            ["claude", "--print", "--model", CLAUDE_MODEL],
            input=prompt, capture_output=True, text=True, timeout=60,
        )
        if r.returncode != 0:
            print(f"      (claude cli failed rc={r.returncode}: {r.stderr.strip()[:200]})")
            return None
        return r.stdout.strip() or None
    except FileNotFoundError:
        return None  # cli not installed
    except Exception as e:
        print(f"      (intuition generation error: {e})")
        return None


def generate_intuition(problem_data):
    """Produce a 3-line revision note. Prefers Anthropic API (works in CI), falls back to `claude` CLI."""
    stmt = (problem_data.get("statement_md") or "")[:2500]
    code = problem_data.get("code") or ""
    if not code:
        return None
    prompt = INTUITION_PROMPT.format(
        title=problem_data["title"],
        difficulty=problem_data["difficulty"],
        statement=stmt,
        lang=problem_data.get("lang_verbose") or "code",
        code=code[:4000],
    )
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if api_key:
        return _intuition_via_api(prompt, api_key)
    return _intuition_via_cli(prompt)


def fetch_problem_full(session, q):
    """Fetch problem statement + latest AC submission code. Returns a dict."""
    slug = q["titleSlug"]
    out = {
        "frontendQuestionId": q["frontendQuestionId"],
        "title": q["title"],
        "titleSlug": slug,
        "difficulty": q["difficulty"],
        "acRate": q["acRate"],
        "topicTags": q["topicTags"],
    }

    qd = fetch_question(session, slug)
    time.sleep(THROTTLE_SEC)
    out["statement_md"] = html_to_md(qd.get("content"))

    sub = fetch_latest_ac_submission(session, slug)
    time.sleep(THROTTLE_SEC)
    if sub:
        try:
            det = fetch_submission_detail(session, sub["id"])
            time.sleep(THROTTLE_SEC)
            lang_name = (det.get("lang") or {}).get("name", sub.get("lang", "")) or ""
            out["code"] = det.get("code", "")
            out["lang_name"] = lang_name
            out["lang_verbose"] = (det.get("lang") or {}).get("verboseName", lang_name)
            out["md_lang"] = LANG_MAP.get(lang_name.lower(), lang_name.lower() or "text")
            out["runtime"] = det.get("runtime", sub.get("runtime", ""))
            out["memory"] = det.get("memory", sub.get("memory", ""))
            out["submitted_at"] = det.get("timestamp") or sub.get("timestamp")
        except Exception as e:
            out["fetch_error"] = str(e)
    return out


def load_state():
    if STATE_FILE.exists():
        return json.loads(STATE_FILE.read_text())
    # Migrate from legacy solved.json if present (no code/intuition, just list)
    return {"problems": {}}


def save_state(state):
    STATE_FILE.write_text(json.dumps(state, indent=2))


def build_md(state):
    problems = state["problems"]
    all_q = list(problems.values())

    # Tag popularity across solved set — used to pick primary topic (rarest = most specific)
    tag_count = Counter()
    for q in all_q:
        for t in q["topicTags"]:
            tag_count[t["name"]] += 1

    def primary_topic(q):
        # Rarest tag wins (more specific = usually the actual technique).
        # Tiebreak on original order in problem's tag list (LeetCode usually lists key tag first).
        if not q["topicTags"]:
            return "Other"
        return min(
            enumerate(q["topicTags"]),
            key=lambda pair: (tag_count[pair[1]["name"]], pair[0]),
        )[1]["name"]

    # Assign each problem to exactly one primary topic
    by_primary = defaultdict(list)
    for q in all_q:
        by_primary[primary_topic(q)].append(q)

    topic_order = sorted(by_primary.keys(), key=lambda t: (-len(by_primary[t]), t))
    c = Counter(q["difficulty"] for q in all_q)
    diff_rank = {"Easy": 0, "Medium": 1, "Hard": 2}

    lines = []
    lines.append("# LeetCode Solved Problems — Revision Sheet")
    lines.append("")
    lines.append(f"**Total: {len(all_q)}**  |  Easy: {c['Easy']}  |  Medium: {c['Medium']}  |  Hard: {c['Hard']}")
    lines.append("")
    lines.append("Each problem is filed under its most specific topic tag (rarest tag it carries).")
    lines.append("")
    lines.append("**Jump to a topic:**")
    lines.append("")
    for t in topic_order:
        header = f"{t} ({len(by_primary[t])})"
        lines.append(f"- [{header}](#{topic_anchor(header)})")
    lines.append("")

    for topic in topic_order:
        header = f"{topic} ({len(by_primary[topic])})"
        lines.append(f"## {header}")
        lines.append("")
        probs = sorted(by_primary[topic], key=lambda q: (diff_rank.get(q["difficulty"], 3), int(q["frontendQuestionId"])))
        for q in probs:
            lines.extend(render_problem(q))
        lines.append("---")
        lines.append("")

    OUTPUT_MD.write_text("\n".join(lines) + "\n")




def topic_anchor(topic):
    # GitHub-flavored anchor: lowercase, spaces->dashes, strip punctuation
    a = topic.lower()
    a = re.sub(r"[^a-z0-9 -]", "", a)
    a = a.replace(" ", "-")
    a = re.sub(r"-+", "-", a).strip("-")
    return a


DIFF_BADGE = {"Easy": "🟢", "Medium": "🟡", "Hard": "🔴"}


def render_problem(q):
    tags = ", ".join(t["name"] for t in q["topicTags"])
    submitted = ""
    if q.get("submitted_at"):
        try:
            submitted = time.strftime("%Y-%m-%d", time.gmtime(int(q["submitted_at"])))
        except Exception:
            pass

    badge = DIFF_BADGE.get(q["difficulty"], "")
    lines = []
    lines.append(f"### {badge} {q['frontendQuestionId']}. {q['title']}")
    lines.append("")
    meta = [f"**{q['difficulty']}**", f"🏷️ {tags}"]
    if submitted:
        meta.append(f"📅 {submitted}")
    lines.append(" · ".join(meta))
    lines.append("")

    lines.append("#### 📄 Problem")
    lines.append("")
    lines.append(q.get("statement_md") or "_(no statement)_")
    lines.append("")

    intuition = (q.get("intuition") or "").strip()
    lines.append("#### 💡 Revision note")
    lines.append("")
    if intuition:
        lines.append("```text")
        lines.append(intuition)
        lines.append("```")
    else:
        lines.append("_(not generated yet — run `python3 sync.py` to fill this in)_")
    lines.append("")

    if q.get("code"):
        lang_verbose = q.get("lang_verbose") or "code"
        md_lang = q.get("md_lang") or "text"
        lines.append(f"<details><summary><b>🧩 Solution ({lang_verbose}) — click to expand</b></summary>")
        lines.append("")
        lines.append(f"```{md_lang}")
        lines.append(q["code"])
        lines.append("```")
        lines.append("")
        lines.append("</details>")
        lines.append("")
    elif q.get("fetch_error"):
        lines.append(f"_Solution fetch failed: {q['fetch_error']}_")
        lines.append("")
    else:
        lines.append("_(no accepted submission found)_")
        lines.append("")

    return lines


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--full", action="store_true",
                    help="Re-fetch every problem, overwriting cache")
    ap.add_argument("--regen-notes", action="store_true",
                    help="Regenerate intuition notes for every problem")
    ap.add_argument("--no-notes", action="store_true",
                    help="Skip claude-generated intuition notes")
    ap.add_argument("--problem", metavar="SLUG",
                    help="Sync just one problem (by titleSlug, e.g. two-sum)")
    args = ap.parse_args()

    session = get_session()
    state = load_state()

    print("Fetching AC-solved list from LeetCode...")
    all_q = fetch_ac_list(session)
    print(f"You've solved {len(all_q)} problems.")

    # Decide which problems to (re)fetch
    if args.problem:
        todo_fetch = [q for q in all_q if q["titleSlug"] == args.problem]
        if not todo_fetch:
            sys.exit(f"No AC-solved problem with slug {args.problem!r}")
    elif args.full:
        todo_fetch = all_q
    else:
        todo_fetch = [q for q in all_q if q["titleSlug"] not in state["problems"]]

    print(f"Fetching {len(todo_fetch)} problem(s) from API...")
    for i, q in enumerate(todo_fetch, 1):
        print(f"  [{i}/{len(todo_fetch)}] {q['frontendQuestionId']}. {q['title']} ({q['difficulty']})")
        try:
            data = fetch_problem_full(session, q)
            state["problems"][q["titleSlug"]] = data
            save_state(state)  # save incrementally so a crash doesn't lose progress
        except Exception as e:
            print(f"      ERROR: {e}")
            time.sleep(2)

    # Prune any problems that are no longer in the AC list (e.g. deleted account, unsolved somehow)
    ac_slugs = {q["titleSlug"] for q in all_q}
    stale = [s for s in state["problems"] if s not in ac_slugs]
    for s in stale:
        print(f"  Removing stale entry: {s}")
        del state["problems"][s]
    if stale:
        save_state(state)

    # Generate intuition notes
    if not args.no_notes:
        if args.regen_notes:
            todo_notes = list(state["problems"].values())
        else:
            todo_notes = [p for p in state["problems"].values() if not p.get("intuition")]

        has_llm = bool(os.environ.get("ANTHROPIC_API_KEY")) or shutil.which("claude") is not None

        if todo_notes and not has_llm:
            print(f"Skipping {len(todo_notes)} intuition note(s): no ANTHROPIC_API_KEY set and `claude` CLI not found.")
            print("Placeholders will show in solved.md; run locally (with `claude` CLI) to fill them in.")
        elif todo_notes:
            print(f"Generating {len(todo_notes)} intuition note(s)...")
            build_md(state)
            for i, p in enumerate(todo_notes, 1):
                print(f"  [{i}/{len(todo_notes)}] {p['frontendQuestionId']}. {p['title']}")
                note = generate_intuition(p)
                if note:
                    p["intuition"] = note
                    save_state(state)
                if i % 10 == 0 or i == len(todo_notes):
                    build_md(state)
        else:
            print("All notes up to date.")

    print("Rebuilding solved.md...")
    build_md(state)
    print(f"Done. Open: {OUTPUT_MD}")


if __name__ == "__main__":
    main()
